modelmanager_version: 0.2.dev2

saved_object:
    alt_capacity: null
    alt_filters: null
    alt_sample_size: 10
    alternatives:
    - jobs
    - buildings
    - parcels
    - zones
    choice_column: null
    chooser_filters:
    - age < 115
    - income < 98
    - edu < 98
    chooser_sample_size: null
    chooser_size: null
    choosers:
    - persons
    - households
    constrained_choices: true
    fitted_parameters:
    - -5.98952485843325e-05
    - -0.07641817440525922
    - -0.651915850308825
    - -0.42008303006265124
    - -0.21677352448303036
    - 0.39492473034944525
    - -1.1111078092272109
    - -0.8052763398706463
    - -1.5661457802771697
    - -0.6999583577383708
    - 0.9946227385872541
    - -1.4144506890905084
    - -0.8224584727925932
    - -1.204159266478964
    - 0.6345406606061823
    - -0.5511773414147771
    - -2.0381203296618056
    - 1.112030633613059
    - -0.6502289795297467
    - -1.2857116001987652
    - 0.5101576402229537
    - -1.989264733892002
    - -1.2069018132386586
    - 0.7464273537535571
    max_iter: null
    model_expression: dist + np.log1p(gen_tt_CAR) + np.log1p(gen_cost_CAR):(hh_inc_under_25k
        + hh_inc_25_to_75k + hh_inc_75_to_200k) + no_higher_ed:(sector_retail + sector_fire
        + sector_healthcare + sector_tech + sector_mfg + sector_food_and_hosp + sector_edu_serv
        + sector_gov) + sector_retail + sector_tech + sector_mfg + sector_food_and_hosp
        + sector_edu_serv + sector_oth_serv + sector_constr + sector_gov + sector_whlsale
        + sector_admin + sector_util - 1
    name: WLCM_gen_tt_simple
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - worker == 1
    - work_at_home == 0
    - zone_id_home == zone_id_home
    out_choosers: null
    out_column: job_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,928\nModel:\
        \         Multinomial Logit   Df Residuals:              7,904\nMethod:  \
        \     Maximum Likelihood   Df Model:                     24\nDate:       \
        \          2019-09-10   Pseudo R-squ.:             0.503\nTime:          \
        \            15:16   Pseudo R-bar-squ.:         0.502\nAIC:              \
        \    18,179.324   Log-Likelihood:       -9,065.662\nBIC:                 \
        \ 18,346.800   LL-Null:             -18,254.895\n=============================================================================================\n\
        \                                              coef   std err         z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        dist                                       -0.0001     0.000   -60.579   \
        \  0.000             \nnp.log1p(gen_tt_CAR)                       -0.0764\
        \     0.018    -4.233     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_under_25k\
        \    -0.6519     0.046   -14.044     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_25_to_75k\
        \    -0.4201     0.021   -19.673     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_75_to_200k\
        \   -0.2168     0.016   -13.155     0.000             \nno_higher_ed:sector_retail\
        \                  0.3949     0.109     3.627     0.000             \nno_higher_ed:sector_fire\
        \                   -1.1111     0.114    -9.742     0.000             \nno_higher_ed:sector_healthcare\
        \             -0.8053     0.088    -9.196     0.000             \nno_higher_ed:sector_tech\
        \                   -1.5661     0.083   -18.955     0.000             \nno_higher_ed:sector_mfg\
        \                    -0.7000     0.118    -5.933     0.000             \n\
        no_higher_ed:sector_food_and_hosp           0.9946     0.172     5.791   \
        \  0.000             \nno_higher_ed:sector_edu_serv               -1.4145\
        \     0.128   -11.071     0.000             \nno_higher_ed:sector_gov    \
        \                -0.8225     0.118    -6.971     0.000             \nsector_retail\
        \                              -1.2042     0.081   -14.862     0.000     \
        \        \nsector_tech                                 0.6345     0.046  \
        \  13.679     0.000             \nsector_mfg                             \
        \    -0.5512     0.072    -7.633     0.000             \nsector_food_and_hosp\
        \                       -2.0381     0.140   -14.536     0.000            \
        \ \nsector_edu_serv                             1.1120     0.062    17.832\
        \     0.000             \nsector_oth_serv                            -0.6502\
        \     0.081    -8.034     0.000             \nsector_constr              \
        \                -1.2857     0.100   -12.884     0.000             \nsector_gov\
        \                                  0.5102     0.073     6.967     0.000  \
        \           \nsector_whlsale                             -1.9893     0.147\
        \   -13.522     0.000             \nsector_admin                         \
        \      -1.2069     0.109   -11.043     0.000             \nsector_util   \
        \                              0.7464     0.146     5.100     0.000      \
        \       \n============================================================================================="
    tags:
    - max
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev2
