modelmanager_version: 0.1.2

saved_object:
    alt_capacity: null
    alt_filters: null
    alt_sample_size: 10
    alternatives:
    - jobs
    - buildings
    - parcels
    - zones
    choice_column: null
    chooser_filters: &id001
    - age < 115
    - income < 98
    - edu < 98
    chooser_sample_size: null
    chooser_size: null
    choosers:
    - persons
    - households
    constrained_choices: true
    fitted_parameters:
    - 0.009994915095949602
    - -0.00010221247656673679
    - -0.21873328137775716
    - 1.0386751902901705e-05
    - -0.03524332649594374
    - -0.11950068430590403
    - -0.6113327715585878
    - -0.4618020210694673
    - -0.17328882820607447
    - 0.4887442699939705
    - -1.0740016245938582
    - -0.7208630965417003
    - -1.587222511366866
    - -0.6451272485256928
    - 1.0583182784835636
    - -1.4669378578810583
    - -0.7475477273658199
    - -1.2859325069630718
    - 0.6765365405777933
    - -0.4964448937402048
    - -2.023656152390891
    - 1.0873209156343526
    - -0.62087953248985
    - -1.2138016831694614
    - 0.4385667943866184
    - -1.9649536905097096
    - -1.130735062072046
    - 0.6821225350108779
    max_iter: null
    model_expression: np.log1p(gen_tt_CAR):np.log1p(gen_tt_WALK_TRANSIT) + dist *
        (np.log1p(gen_tt_CAR)) + np.log1p(gen_tt_WALK_TRANSIT) + np.log1p(total_jobs_gen_tt_WALK_TRANSIT_45)
        + np.log1p(gen_cost_CAR):(hh_inc_under_25k + hh_inc_25_to_75k + hh_inc_75_to_200k)
        + no_higher_ed:(sector_retail + sector_fire + sector_healthcare + sector_tech
        + sector_mfg + sector_food_and_hosp + sector_edu_serv + sector_gov) + sector_retail
        + sector_tech + sector_mfg + sector_food_and_hosp + sector_edu_serv + sector_oth_serv
        + sector_constr + sector_gov + sector_whlsale + sector_admin + sector_util
        - 1
    name: WLCM_gen_tt
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters: *id001
    out_choosers: null
    out_column: job_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,928\nModel:\
        \         Multinomial Logit   Df Residuals:              7,900\nMethod:  \
        \     Maximum Likelihood   Df Model:                     28\nDate:       \
        \          2019-06-17   Pseudo R-squ.:             0.508\nTime:          \
        \            12:28   Pseudo R-bar-squ.:         0.507\nAIC:              \
        \    18,010.223   Log-Likelihood:       -8,977.112\nBIC:                 \
        \ 18,205.612   LL-Null:             -18,254.895\n=======================================================================================================\n\
        \                                                        coef   std err  \
        \       z     P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------------------\n\
        np.log1p(gen_tt_CAR):np.log1p(gen_tt_WALK_TRANSIT)    0.0100     0.014   \
        \  0.718     0.472             \ndist                                    \
        \             -0.0001     0.000   -13.943     0.000             \nnp.log1p(gen_tt_CAR)\
        \                                 -0.2187     0.082    -2.660     0.008  \
        \           \ndist:np.log1p(gen_tt_CAR)                             0.0000\
        \     0.000     6.874     0.000             \nnp.log1p(gen_tt_WALK_TRANSIT)\
        \                        -0.0352     0.037    -0.950     0.342           \
        \  \nnp.log1p(total_jobs_gen_tt_WALK_TRANSIT_45)          -0.1195     0.015\
        \    -8.080     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_under_25k\
        \              -0.6113     0.040   -15.324     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_25_to_75k\
        \              -0.4618     0.019   -24.539     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_75_to_200k\
        \             -0.1733     0.014   -12.014     0.000             \nno_higher_ed:sector_retail\
        \                            0.4887     0.110     4.444     0.000        \
        \     \nno_higher_ed:sector_fire                             -1.0740     0.112\
        \    -9.554     0.000             \nno_higher_ed:sector_healthcare       \
        \                -0.7209     0.092    -7.797     0.000             \nno_higher_ed:sector_tech\
        \                             -1.5872     0.084   -18.950     0.000      \
        \       \nno_higher_ed:sector_mfg                              -0.6451   \
        \  0.116    -5.548     0.000             \nno_higher_ed:sector_food_and_hosp\
        \                     1.0583     0.171     6.173     0.000             \n\
        no_higher_ed:sector_edu_serv                         -1.4669     0.127   -11.531\
        \     0.000             \nno_higher_ed:sector_gov                        \
        \      -0.7475     0.118    -6.359     0.000             \nsector_retail \
        \                                       -1.2859     0.084   -15.258     0.000\
        \             \nsector_tech                                           0.6765\
        \     0.048    13.956     0.000             \nsector_mfg                 \
        \                          -0.4964     0.074    -6.748     0.000         \
        \    \nsector_food_and_hosp                                 -2.0237     0.138\
        \   -14.639     0.000             \nsector_edu_serv                      \
        \                 1.0873     0.063    17.163     0.000             \nsector_oth_serv\
        \                                      -0.6209     0.084    -7.411     0.000\
        \             \nsector_constr                                        -1.2138\
        \     0.102   -11.925     0.000             \nsector_gov                 \
        \                           0.4386     0.074     5.943     0.000         \
        \    \nsector_whlsale                                       -1.9650     0.150\
        \   -13.064     0.000             \nsector_admin                         \
        \                -1.1307     0.114    -9.886     0.000             \nsector_util\
        \                                           0.6821     0.146     4.688   \
        \  0.000             \n======================================================================================================="
    tags:
    - max
    template: LargeMultinomialLogitStep
    template_version: 0.1.2
