modelmanager_version: 0.1.2

saved_object:
    alt_capacity: null
    alt_filters: null
    alt_sample_size: 10
    alternatives:
    - jobs
    - buildings
    - parcels
    - zones
    choice_column: null
    chooser_filters:
    - age < 115
    - income < 98
    - edu < 98
    chooser_sample_size: null
    chooser_size: null
    choosers:
    - persons
    - households
    constrained_choices: true
    fitted_parameters:
    - 0.04496435035298315
    - -9.9123717053718e-05
    - -4
    - 9.27582624026469e-06
    - -0.15621664659705028
    - -0.06111003315269964
    - -0.4887253865529219
    - -0.3936017348363237
    - -0.15312066816800923
    - 0.30943643186362485
    - -1.123189861221489
    - -0.7766707874187231
    - -1.564364724949148
    - -0.650242547978425
    - 1.0236291219329199
    - -1.38674466920115
    - -0.6528952296841796
    - -1.1849390613715483
    - 0.6547351908168072
    - -0.5517078769771097
    - -2.0921088177471874
    - 1.0573995729314252
    - -0.6721190810458257
    - -1.2509677098100385
    - 0.43471714518366
    - -2.0188011859721087
    - -1.2373546555095571
    - 0.84707636954069
    max_iter: null
    model_expression: np.log1p(gen_tt_CAR):np.log1p(gen_tt_WALK_TRANSIT) + dist *
        (np.log1p(gen_tt_CAR)) + np.log1p(gen_tt_WALK_TRANSIT) + np.log1p(total_jobs_gen_tt_WALK_TRANSIT_15)
        + np.log1p(gen_cost_CAR):(hh_inc_under_25k + hh_inc_25_to_75k + hh_inc_75_to_200k)
        + no_higher_ed:(sector_retail + sector_fire + sector_healthcare + sector_tech
        + sector_mfg + sector_food_and_hosp + sector_edu_serv + sector_gov) + sector_retail
        + sector_tech + sector_mfg + sector_food_and_hosp + sector_edu_serv + sector_oth_serv
        + sector_constr + sector_gov + sector_whlsale + sector_admin + sector_util
        - 1
    name: WLCM_gen_tt_TWEAK
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - worker == 1
    - work_at_home == 0
    - zone_id_home == zone_id_home
    out_choosers: null
    out_column: job_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,928\nModel:\
        \         Multinomial Logit   Df Residuals:              7,900\nMethod:  \
        \     Maximum Likelihood   Df Model:                     28\nDate:       \
        \          2019-06-17   Pseudo R-squ.:             0.505\nTime:          \
        \            13:58   Pseudo R-bar-squ.:         0.503\nAIC:              \
        \    18,131.535   Log-Likelihood:       -9,037.767\nBIC:                 \
        \ 18,326.923   LL-Null:             -18,254.895\n=======================================================================================================\n\
        \                                                        coef   std err  \
        \       z     P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------------------\n\
        np.log1p(gen_tt_CAR):np.log1p(gen_tt_WALK_TRANSIT)    0.0450     0.012   \
        \  3.854     0.000             \ndist                                    \
        \             -0.0001     0.000   -13.666     0.000             \nnp.log1p(gen_tt_CAR)\
        \                                 -0.3940     0.073    -5.433     0.000  \
        \           \ndist:np.log1p(gen_tt_CAR)                             0.0000\
        \     0.000     6.282     0.000             \nnp.log1p(gen_tt_WALK_TRANSIT)\
        \                        -0.1562     0.028    -5.493     0.000           \
        \  \nnp.log1p(total_jobs_gen_tt_WALK_TRANSIT_15)          -0.0611     0.012\
        \    -5.021     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_under_25k\
        \              -0.4887     0.040   -12.322     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_25_to_75k\
        \              -0.3936     0.019   -20.886     0.000             \nnp.log1p(gen_cost_CAR):hh_inc_75_to_200k\
        \             -0.1531     0.014   -10.589     0.000             \nno_higher_ed:sector_retail\
        \                            0.3094     0.108     2.858     0.004        \
        \     \nno_higher_ed:sector_fire                             -1.1232     0.113\
        \    -9.936     0.000             \nno_higher_ed:sector_healthcare       \
        \                -0.7767     0.089    -8.691     0.000             \nno_higher_ed:sector_tech\
        \                             -1.5644     0.083   -18.782     0.000      \
        \       \nno_higher_ed:sector_mfg                              -0.6502   \
        \  0.118    -5.503     0.000             \nno_higher_ed:sector_food_and_hosp\
        \                     1.0236     0.169     6.051     0.000             \n\
        no_higher_ed:sector_edu_serv                         -1.3867     0.126   -10.966\
        \     0.000             \nno_higher_ed:sector_gov                        \
        \      -0.6529     0.120    -5.430     0.000             \nsector_retail \
        \                                       -1.1849     0.082   -14.388     0.000\
        \             \nsector_tech                                           0.6547\
        \     0.048    13.523     0.000             \nsector_mfg                 \
        \                          -0.5517     0.074    -7.446     0.000         \
        \    \nsector_food_and_hosp                                 -2.0921     0.137\
        \   -15.301     0.000             \nsector_edu_serv                      \
        \                 1.0574     0.064    16.469     0.000             \nsector_oth_serv\
        \                                      -0.6721     0.082    -8.202     0.000\
        \             \nsector_constr                                        -1.2510\
        \     0.099   -12.643     0.000             \nsector_gov                 \
        \                           0.4347     0.074     5.911     0.000         \
        \    \nsector_whlsale                                       -2.0188     0.151\
        \   -13.369     0.000             \nsector_admin                         \
        \                -1.2374     0.108   -11.429     0.000             \nsector_util\
        \                                           0.8471     0.161     5.259   \
        \  0.000             \n======================================================================================================="
    tags:
    - max
    template: LargeMultinomialLogitStep
    template_version: 0.1.2
